from __future__ import annotations

import platform

STRATEGY_ID = "BTC_ETH_PA_STRATEGY"
STRATEGY_VERSION = "BTC_ETH_PA_STRATEGY_V1_1"
STRATEGY_CANDIDATE_SCHEMA_VERSION = "STRATEGY_CANDIDATE_SCHEMA_V1"
VALIDATION_FAILURE_SCHEMA_VERSION = "VALIDATION_FAILURE_SCHEMA_V1"
INDICATOR_CONFIG_VERSION = "INDICATOR_CONFIG_V1"
DECISION_VISIBLE_INPUT_VERSION = "DECISION_VISIBLE_INPUT_V1"
PRE_ROLL_POLICY_VERSION = "PRE_ROLL_POLICY_V1_EXACT_250D_100X4H"

ENTRY_INTENT_SCHEMA_VERSION = "ENTRY_INTENT_SCHEMA_V1"
TARGET_MINUTE_OPEN_SNAPSHOT_SCHEMA_VERSION = "TARGET_MINUTE_OPEN_SNAPSHOT_SCHEMA_V1"
TARGET_EVENT_WATERMARK_SCHEMA_VERSION = "TARGET_EVENT_WATERMARK_SCHEMA_V1"
ENTRY_EXECUTION_PLAN_SCHEMA_VERSION = "ENTRY_EXECUTION_PLAN_SCHEMA_V1"
EXIT_INTENT_SCHEMA_VERSION = "EXIT_INTENT_SCHEMA_V1"
EXIT_EXECUTION_PLAN_SCHEMA_VERSION = "EXIT_EXECUTION_PLAN_SCHEMA_V1"
EXECUTION_REJECTION_SCHEMA_VERSION = "EXECUTION_REJECTION_SCHEMA_V1"
REJECTION_SUBJECT_REF_SCHEMA_VERSION = "REJECTION_SUBJECT_REF_SCHEMA_V1"
CONTRACT_RULE_COVERAGE_VERSION = "CONTRACT_RULE_COVERAGE_V1"
CONTRACT_APPROXIMATION_POLICY_VERSION = "CONTRACT_APPROXIMATION_POLICY_V1"
COST_MODEL_SNAPSHOT_SCHEMA_VERSION = "COST_MODEL_SNAPSHOT_SCHEMA_V1"
POSITION_SIZING_RESULT_SCHEMA_VERSION = "POSITION_SIZING_RESULT_SCHEMA_V1"
PORTFOLIO_PLANNING_BATCH_SCHEMA_VERSION = "PORTFOLIO_PLANNING_BATCH_SCHEMA_V1"
PORTFOLIO_BATCH_COMPLETENESS_SNAPSHOT_SCHEMA_VERSION = (
    "PORTFOLIO_BATCH_COMPLETENESS_SNAPSHOT_SCHEMA_V1"
)
PORTFOLIO_BATCH_COMPLETENESS_POLICY_VERSION = "PORTFOLIO_BATCH_COMPLETENESS_POLICY_V1"
PORTFOLIO_SCALING_RESULT_SCHEMA_VERSION = "PORTFOLIO_SCALING_RESULT_SCHEMA_V1"
ACCEPTED_SCALING_ITEM_SCHEMA_VERSION = "ACCEPTED_SCALING_ITEM_SCHEMA_V1"
REJECTED_SCALING_ITEM_SCHEMA_VERSION = "REJECTED_SCALING_ITEM_SCHEMA_V1"
ACCOUNT_PLANNING_SNAPSHOT_SCHEMA_VERSION = "ACCOUNT_PLANNING_SNAPSHOT_SCHEMA_V1"
ACCOUNT_PLANNING_EVIDENCE_BUNDLE_SCHEMA_VERSION = "ACCOUNT_PLANNING_EVIDENCE_BUNDLE_SCHEMA_V1"
ACCOUNT_EQUITY_MODEL_VERSION = "ACCOUNT_EQUITY_MODEL_V1"
VALUATION_BASIS_VERSION = "MARK_PRICE_OPEN_AT_ELIGIBLE_TIME_V1"
PLANNING_PHASE_VERSION = "PLANNING_PHASE_V1"
FUNDING_SCHEDULE_SNAPSHOT_SCHEMA_VERSION = "FUNDING_SCHEDULE_SNAPSHOT_SCHEMA_V1"
FUNDING_RISK_CONFIG_SNAPSHOT_SCHEMA_VERSION = "FUNDING_RISK_CONFIG_SNAPSHOT_V1"
EXIT_CONDITION_SNAPSHOT_VERSION = "EXIT_CONDITION_SNAPSHOT_V1"
EXECUTION_TIME_CONFIG_VERSION = "EXECUTION_TIME_CONFIG_V1"
MAX_HOLD_VERSION = "MAX_HOLD_V1_EXACT_48H"
GAP_POLICY_VERSION = "GAP_POLICY_V1"
PRICE_GEOMETRY_VERSION = "PRICE_GEOMETRY_V1"
FEE_MODEL_VERSION = "FEE_MODEL_V1"
SLIPPAGE_MODEL_VERSION = "SLIPPAGE_MODEL_V1"
RESERVE_PRICE_BASIS_VERSION = "RESERVE_PRICE_BASIS_V1"
FUNDING_BUFFER_MODEL_VERSION = "FUNDING_BUFFER_MODEL_V2"
FUNDING_RISK_CONFIG_VERSION = "FUNDING_RISK_CONFIG_V1"
POSITION_SIZING_MODEL_VERSION = "POSITION_SIZING_MODEL_V2"
PORTFOLIO_SCALING_MODEL_VERSION = "PORTFOLIO_SCALING_MODEL_V2"
CONTRACT_MINIMUM_VERSION = "CONTRACT_MINIMUM_V1"
LEVERAGE_POLICY_VERSION = "LEVERAGE_POLICY_V1_FIXED_1X"
REJECTION_PRIORITY_VERSION = "2B_REJECTION_PRIORITY_V2"
REJECTION_SUBJECT_DISPOSITION_VERSION = "2B_REJECTION_SUBJECT_DISPOSITION_V1"
CANONICAL_2B_VERSION = "2B_CANONICAL_VERSION_V1"
MASTER_TEST_REGISTRY_VERSION = "MASTER_TEST_REGISTRY_V1"

EMA_VERSION = "EMA_RECURSIVE_V1_FLOAT64"
ATR_VERSION = "ATR_WILDER_V1_FLOAT64"
DONCHIAN_VERSION = "DONCHIAN_PREVIOUS_20_V1_DECIMAL"
NUMERIC_BOUNDARY_VERSION = "FLOAT64_TO_DECIMAL_15SIG_HALF_EVEN_V1"

LOCKED_PYTHON_IMPLEMENTATION = "CPython"
LOCKED_PYTHON_VERSION = "3.12.13"


def assert_runtime_lock() -> None:
    implementation = platform.python_implementation()
    version = platform.python_version()
    if (implementation, version) != (LOCKED_PYTHON_IMPLEMENTATION, LOCKED_PYTHON_VERSION):
        raise RuntimeError(
            "INDICATOR_CONFIG_V1 requires "
            f"{LOCKED_PYTHON_IMPLEMENTATION} {LOCKED_PYTHON_VERSION}; "
            f"received {implementation} {version}"
        )
