from __future__ import annotations

import platform

STRATEGY_ID = "BTC_ETH_PA_STRATEGY"
STRATEGY_VERSION = "BTC_ETH_PA_STRATEGY_V1_1"
STRATEGY_CANDIDATE_SCHEMA_VERSION = "STRATEGY_CANDIDATE_SCHEMA_V1"
VALIDATION_FAILURE_SCHEMA_VERSION = "VALIDATION_FAILURE_SCHEMA_V1"
INDICATOR_CONFIG_VERSION = "INDICATOR_CONFIG_V1"
DECISION_VISIBLE_INPUT_VERSION = "DECISION_VISIBLE_INPUT_V1"
PRE_ROLL_POLICY_VERSION = "PRE_ROLL_POLICY_V1_EXACT_250D_100X4H"

EMA_VERSION = "EMA_RECURSIVE_V1_FLOAT64"
ATR_VERSION = "ATR_WILDER_V1_FLOAT64"
DONCHIAN_VERSION = "DONCHIAN_PREVIOUS_20_V1_DECIMAL"
NUMERIC_BOUNDARY_VERSION = "FLOAT64_TO_DECIMAL_15SIG_HALF_EVEN_V1"

LOCKED_PYTHON_IMPLEMENTATION = "CPython"
LOCKED_PYTHON_VERSION = "3.12.13"


def assert_runtime_lock() -> None:
    implementation = platform.python_implementation()
    version = platform.python_version()
    if (implementation, version) != (LOCKED_PYTHON_IMPLEMENTATION, LOCKED_PYTHON_VERSION):
        raise RuntimeError(
            "INDICATOR_CONFIG_V1 requires "
            f"{LOCKED_PYTHON_IMPLEMENTATION} {LOCKED_PYTHON_VERSION}; "
            f"received {implementation} {version}"
        )

