SIMULATION_CONFIG_VERSION = "SIMULATION_CONFIG_V1"
CANONICAL_VERSION = "CANONICAL_2C_V1"
MINUTE_EVENT_ORDER_VERSION = "MINUTE_EVENT_ORDER_V2"
INTRAMINUTE_HALT_POLICY_VERSION = "INTRAMINUTE_HALT_POLICY_V1"
LIQUIDATION_MODEL_VERSION = "ESTIMATED_FIXED_ISOLATED_MARGIN_V1"
LIQUIDATION_WATERMARK = "ESTIMATED_NOT_EXCHANGE_EXACT"

EVENT_STAGES = (
    "LOAD_CLOSED_INPUTS",
    "FAIL_CLOSED_DATA_GATE",
    "OPENING_POSITION_RECONCILIATION",
    "FUNDING_SETTLEMENT",
    "OPEN_GAP_PROTECTIVE_GATE",
    "SCHEDULED_OPEN_EXITS",
    "OPEN_EQUITY_AND_HALT_GATE",
    "ENTRY_PLANNING_AND_BATCH_GATE",
    "ENTRY_FILLS",
    "INTRAMINUTE_TRIGGER_DISCOVERY",
    "AMBIGUITY_POLICY_SELECTION",
    "PROTECTIVE_OR_LIQUIDATION_EXITS",
    "MARK_TO_MARKET_CLOSE",
    "HALT_AND_CANONICAL_COMMIT",
)
