from enum import StrEnum


class MarketView(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    NO_SETUP = "NO_SETUP"


class MarketReason(StrEnum):
    BULL_DONCHIAN_BREAKOUT = "BULL_DONCHIAN_BREAKOUT"
    BEAR_DONCHIAN_BREAKOUT = "BEAR_DONCHIAN_BREAKOUT"
    TREND_NEUTRAL = "TREND_NEUTRAL"
    NO_BREAKOUT = "NO_BREAKOUT"
    BREAKOUT_AGAINST_TREND = "BREAKOUT_AGAINST_TREND"


class TrendState(StrEnum):
    BULL = "BULL"
    BEAR = "BEAR"
    NEUTRAL = "NEUTRAL"


class ValidationReason(StrEnum):
    DECISION_BEFORE_TRAINING_START = "DECISION_BEFORE_TRAINING_START"
    PRE_ROLL_INSUFFICIENT = "PRE_ROLL_INSUFFICIENT"
    DATA_SEGMENT_NOT_CONTINUOUS = "DATA_SEGMENT_NOT_CONTINUOUS"
    NATIVE_AGGREGATION_NOT_VALID = "NATIVE_AGGREGATION_NOT_VALID"
    DAILY_BAR_NOT_AVAILABLE = "DAILY_BAR_NOT_AVAILABLE"
    INDICATOR_WARMING_UP = "INDICATOR_WARMING_UP"
    INDICATOR_NON_FINITE_OR_NON_POSITIVE = "INDICATOR_NON_FINITE_OR_NON_POSITIVE"
    INDICATOR_BOUNDARY_INVALID = "INDICATOR_BOUNDARY_INVALID"
    DECISION_VISIBLE_INPUT_HASH_MISMATCH = "DECISION_VISIBLE_INPUT_HASH_MISMATCH"
    SCHEMA_VERSION_UNSUPPORTED = "SCHEMA_VERSION_UNSUPPORTED"
    UNCLOSED_BAR = "UNCLOSED_BAR"
