from enum import StrEnum


class Side(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"


class ContractRuleMode(StrEnum):
    VERIFIED = "VERIFIED"
    APPROXIMATED = "APPROXIMATED"
    UNAVAILABLE = "UNAVAILABLE"


class FundingRiskVerificationMode(StrEnum):
    VERIFIED = "VERIFIED"
    APPROXIMATED = "APPROXIMATED"
    UNAVAILABLE = "UNAVAILABLE"


class ResearchStage(StrEnum):
    BACKTEST = "BACKTEST"
    PAPER_SIMULATION = "PAPER_SIMULATION"
    LIVE_ELIGIBILITY_RESEARCH = "LIVE_ELIGIBILITY_RESEARCH"


class ApproximationDirection(StrEnum):
    PRIOR_ONLY_APPROXIMATION = "PRIOR_ONLY_APPROXIMATION"
    HINDSIGHT_DIAGNOSTIC_APPROXIMATION = "HINDSIGHT_DIAGNOSTIC_APPROXIMATION"


class ContractRuleReviewStatus(StrEnum):
    APPROVED_VERIFIED = "APPROVED_VERIFIED"
    APPROVED_PRIOR_ONLY = "APPROVED_PRIOR_ONLY"
    APPROVED_HINDSIGHT_DIAGNOSTIC = "APPROVED_HINDSIGHT_DIAGNOSTIC"


class PlanningPhase(StrEnum):
    POST_SAME_TIME_FUNDING_AND_SCHEDULED_EXITS_PRE_ENTRY_BATCH_V1 = (
        "POST_SAME_TIME_FUNDING_AND_SCHEDULED_EXITS_PRE_ENTRY_BATCH_V1"
    )


class ValuationBasis(StrEnum):
    MARK_PRICE_OPEN_AT_ELIGIBLE_TIME_V1 = "MARK_PRICE_OPEN_AT_ELIGIBLE_TIME_V1"


class ExperimentState(StrEnum):
    RUNNING = "RUNNING"
    HALTED = "HALTED"


class RejectionDisposition(StrEnum):
    EXPERIMENT_INVALID = "EXPERIMENT_INVALID"
    EXECUTION_PATH_INVALID = "EXECUTION_PATH_INVALID"
    CANDIDATE_REJECTED = "CANDIDATE_REJECTED"
    PLAN_CANCELLED = "PLAN_CANCELLED"


class RejectionSubjectKind(StrEnum):
    CANDIDATE = "CANDIDATE"
    ENTRY_INTENT = "ENTRY_INTENT"
    EXIT_INTENT = "EXIT_INTENT"
    ENTRY_PLAN = "ENTRY_PLAN"
    EXIT_PLAN = "EXIT_PLAN"
    PORTFOLIO_BATCH = "PORTFOLIO_BATCH"


class ExecutionRejectionReason(StrEnum):
    DATA_INVALID = "DATA_INVALID"
    TARGET_MINUTE_UNAVAILABLE = "TARGET_MINUTE_UNAVAILABLE"
    REQUIRED_ACCOUNT_EVIDENCE_UNAVAILABLE = "REQUIRED_ACCOUNT_EVIDENCE_UNAVAILABLE"
    OPEN_RISK_MODEL_UNAVAILABLE = "OPEN_RISK_MODEL_UNAVAILABLE"
    CONTRACT_RULE_UNAVAILABLE = "CONTRACT_RULE_UNAVAILABLE"
    CONTRACT_RULE_EXPIRED = "CONTRACT_RULE_EXPIRED"
    COST_MODEL_UNAVAILABLE = "COST_MODEL_UNAVAILABLE"
    FUNDING_SCHEDULE_UNVERIFIED = "FUNDING_SCHEDULE_UNVERIFIED"
    FUNDING_RISK_CONFIG_UNAVAILABLE = "FUNDING_RISK_CONFIG_UNAVAILABLE"
    BATCH_INCOMPLETE = "BATCH_INCOMPLETE"
    POSITION_SNAPSHOT_CHANGED = "POSITION_SNAPSHOT_CHANGED"
    POSITION_QUANTITY_RULE_MISMATCH = "POSITION_QUANTITY_RULE_MISMATCH"
    EXPERIMENT_HALTED = "EXPERIMENT_HALTED"
    EXISTING_POSITION = "EXISTING_POSITION"
    TOTAL_RISK_ALREADY_AT_LIMIT = "TOTAL_RISK_ALREADY_AT_LIMIT"
    GAP_TOO_LARGE = "GAP_TOO_LARGE"
    PRICE_GEOMETRY_INVALID = "PRICE_GEOMETRY_INVALID"
    INSUFFICIENT_AVAILABLE_BALANCE = "INSUFFICIENT_AVAILABLE_BALANCE"
    QUANTITY_ROUNDED_TO_ZERO = "QUANTITY_ROUNDED_TO_ZERO"
    BELOW_MIN_QTY = "BELOW_MIN_QTY"
    BELOW_MIN_NOTIONAL = "BELOW_MIN_NOTIONAL"
    CANDIDATE_NOT_ACTIONABLE = "CANDIDATE_NOT_ACTIONABLE"


class ResolutionKind(StrEnum):
    SIZING_RESULT = "SIZING_RESULT"
    ECONOMIC_REJECTION = "ECONOMIC_REJECTION"
    EXECUTION_PATH_INVALID = "EXECUTION_PATH_INVALID"
    EXPERIMENT_INVALID = "EXPERIMENT_INVALID"


class MarketView(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    NO_SETUP = "NO_SETUP"


class MarketReason(StrEnum):
    BULL_DONCHIAN_BREAKOUT = "BULL_DONCHIAN_BREAKOUT"
    BEAR_DONCHIAN_BREAKOUT = "BEAR_DONCHIAN_BREAKOUT"
    TREND_NEUTRAL = "TREND_NEUTRAL"
    NO_BREAKOUT = "NO_BREAKOUT"
    BREAKOUT_AGAINST_TREND = "BREAKOUT_AGAINST_TREND"


class TrendState(StrEnum):
    BULL = "BULL"
    BEAR = "BEAR"
    NEUTRAL = "NEUTRAL"


class ValidationReason(StrEnum):
    DECISION_BEFORE_TRAINING_START = "DECISION_BEFORE_TRAINING_START"
    PRE_ROLL_INSUFFICIENT = "PRE_ROLL_INSUFFICIENT"
    DATA_SEGMENT_NOT_CONTINUOUS = "DATA_SEGMENT_NOT_CONTINUOUS"
    NATIVE_AGGREGATION_NOT_VALID = "NATIVE_AGGREGATION_NOT_VALID"
    DAILY_BAR_NOT_AVAILABLE = "DAILY_BAR_NOT_AVAILABLE"
    INDICATOR_WARMING_UP = "INDICATOR_WARMING_UP"
    INDICATOR_NON_FINITE_OR_NON_POSITIVE = "INDICATOR_NON_FINITE_OR_NON_POSITIVE"
    INDICATOR_BOUNDARY_INVALID = "INDICATOR_BOUNDARY_INVALID"
    DECISION_VISIBLE_INPUT_HASH_MISMATCH = "DECISION_VISIBLE_INPUT_HASH_MISMATCH"
    SCHEMA_VERSION_UNSUPPORTED = "SCHEMA_VERSION_UNSUPPORTED"
    UNCLOSED_BAR = "UNCLOSED_BAR"
